version: "2"
services:
    caddy:
        image: abiosoft/caddy
        restart: always
        depends_on:
                - sonarr
                - radarr
                - emby
        ports:
                - "80:80"
                - "443:443"
        volumes:
                - ${USERDIR}/caddy/Caddyfile:/etc/Caddyfile
                - ${USERDIR}/caddy/.caddy:/root/.caddy
